### ISSUE TITLE
Error - Traceback KeyError: 'persistent-others'

### ISSUE THREAD

**Issue by seansgm** [kcrawford/dockutil#24]
dockutil errors when trying to make changes to a plist with no 'persistent-others'.  Should dockutil care that there isn't a persistent-others when writing to persistent-apps or listing contents?

Eg.
sh-3.2# /Library/Future/Scripts/dockutil --list '/System/Library/User Template/English.lproj'
Traceback (most recent call last):
  File "/Library/Future/Scripts/dockutil", line 663, in <module>
    main()
  File "/Library/Future/Scripts/dockutil", line 279, in main
    for item in pl[section]:
KeyError: 'persistent-others'

sh-3.2# /Library/Future/Scripts/dockutil --add /Applications/Firefox.app --no-restart '/System/Library/User Template/English.lproj'
Traceback (most recent call last):
  File "/Library/Future/Scripts/dockutil", line 663, in <module>
    main()
  File "/Library/Future/Scripts/dockutil", line 365, in main
    commitPlist(pl, plist_path, restart_dock)
  File "/Library/Future/Scripts/dockutil", line 618, in commitPlist
    pl = removeLongs(pl)
  File "/Library/Future/Scripts/dockutil", line 649, in removeLongs
    for item in pl['persistent-others']:
KeyError: 'persistent-others'

**Comment by kcrawford** [comment]
Fixed for list and add in master.  Will be in the next release.
