### ISSUE TITLE
dockutil stops working?

### ISSUE THREAD

**Issue by macmarine** [kcrawford/dockutil#71]
If I want to add an application to the dock, I get this error and nothing is happpend. Remove a dock item is working, but I can't add any new items to the dock. 

Any ideas?

```

/usr/local/sbin/dockutil --add '/Applications/Safari.app' --no-restart '/Users/admin'

Traceback (most recent call last):
  File "/usr/local/sbin/dockutil", line 686, in <module>
    main()
  File "/usr/local/sbin/dockutil", line 386, in main
    if addItem(pl, real_add_path, replace_label, position, before_item, after_item, section, displayas, showas, arrangement, tile_type, label_name):
  File "/usr/local/sbin/dockutil", line 547, in addItem
    label_name = label_name.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
```

Tested with macOS 10.11 and 10.12 using the latest version of dockutil

**Comment by kcrawford** [comment]
Sorry seems to be a bug in master.

Try a released version.

I will fix but in the meantime use a release version.

Kyle

**Comment by kcrawford** [comment]
Fixed.  Thanks for reporting.
